// <auto-generated />
using System;
using ItemAuthoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemAuthoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authoring")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PassingScorePercentage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Exams", "authoring", t =>
                        {
                            t.HasCheckConstraint("CK_Exams_PassingScore_Range", "[PassingScorePercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.ExamItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("ScoreOverride")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ScoreOverride");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ExamSectionId", "Position")
                        .IsUnique();

                    b.ToTable("ExamItems", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "Position")
                        .IsUnique();

                    b.ToTable("ExamSections", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockedOutUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("Categories", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaximumScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MaximumScore");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Status");

                    b.HasIndex("Type", "Difficulty");

                    b.ToTable("Items", "authoring", t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Position")
                        .IsUnique();

                    b.ToTable("ItemOptions", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemTag", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaximumScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RubricGuidance")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("RubricMaximumWords")
                        .HasColumnType("int");

                    b.Property<int?>("RubricMinimumWords")
                        .HasColumnType("int");

                    b.Property<string>("StemText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ItemVersions", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tags", "authoring");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ChoiceItem", b =>
                {
                    b.HasBaseType("ItemAuthoring.Domain.Items.Item");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.EssayItem", b =>
                {
                    b.HasBaseType("ItemAuthoring.Domain.Items.Item");

                    b.Property<string>("SampleAnswer")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.EitherOrItem", b =>
                {
                    b.HasBaseType("ItemAuthoring.Domain.Items.ChoiceItem");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.MultipleResponseItem", b =>
                {
                    b.HasBaseType("ItemAuthoring.Domain.Items.ChoiceItem");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.SingleResponseItem", b =>
                {
                    b.HasBaseType("ItemAuthoring.Domain.Items.ChoiceItem");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Items_MaximumScore_Positive", "[MaximumScore] > 0");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.ExamItem", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Exams.ExamSection", null)
                        .WithMany("Items")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemAuthoring.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.ExamSection", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Exams.Exam", null)
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Identity.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemAuthoring.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.User", b =>
                {
                    b.OwnsOne("ItemAuthoring.Domain.Identity.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("DisplayName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ItemAuthoring.Domain.Identity.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("NormalizedEmail");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("Users", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ItemAuthoring.Domain.Identity.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItemAuthoring.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Category", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Items.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Item", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Items.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemOption", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Items.ChoiceItem", null)
                        .WithMany("Options")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemTag", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Items.Item", null)
                        .WithMany("Tags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemAuthoring.Domain.Items.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ItemVersion", b =>
                {
                    b.HasOne("ItemAuthoring.Domain.Items.Item", null)
                        .WithMany("Versions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ItemAuthoring.Domain.Items.ItemVersionOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("ItemVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Position")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Position"));

                            b1.Property<string>("Feedback")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("bit");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("ItemVersionId", "Position");

                            b1.ToTable("ItemVersionOptions", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("ItemVersionId");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Tag", b =>
                {
                    b.OwnsOne("ItemAuthoring.Domain.Items.TagName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("NormalizedName");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Name");

                            b1.HasKey("TagId");

                            b1.HasIndex("Normalized")
                                .IsUnique();

                            b1.ToTable("Tags", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.EssayItem", b =>
                {
                    b.OwnsOne("ItemAuthoring.Domain.Items.EssayRubric", "Rubric", b1 =>
                        {
                            b1.Property<Guid>("EssayItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Guidance")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("RubricGuidance");

                            b1.Property<int>("MaximumWords")
                                .HasColumnType("int")
                                .HasColumnName("RubricMaximumWords");

                            b1.Property<int>("MinimumWords")
                                .HasColumnType("int")
                                .HasColumnName("RubricMinimumWords");

                            b1.HasKey("EssayItemId");

                            b1.ToTable("Items", "authoring");

                            b1.WithOwner()
                                .HasForeignKey("EssayItemId");
                        });

                    b.Navigation("Rubric")
                        .IsRequired();
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Exams.ExamSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.Item", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ItemAuthoring.Domain.Items.ChoiceItem", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
